=== Create a runtime environment and a Liberty server

For optimum development awesomeness, we'll create the Liberty server a little differently than is in the usual 
https://developer.ibm.com/wasdev/downloads/liberty-profile-using-eclipse/[WASdev.net instructions].
We're going to define and customize the runtime environment so that WDT can find the {{ book.wlpcfgDir }} directory
that is part of our project repository.

==== Create a Runtime Environment in Eclipse

1. Open the 'Runtime Explorer' view:
    * *Window -> Show View -> Other*
    * type `runtime` in the filter box to find the view (it's under the Server heading).
2. Right-click in the view, and select *New -> Runtime Environment*
3. Give the Runtime environment a name, e.g. `wlp-2015.6.0.0` if you're using the June 2015 beta.
4. Either:
    * Select an existing installation (something you downloaded earlier), or
    * select *Install from an archive or a repository* to download a new Liberty archive via the wizard
5. Follow the prompts (and possibly choose additional features to install) until you *Finish* creating the Runtime Environment

==== Add the {{ book.wlpcfgDir }} user directory to the Runtime Environment, and create a server

1. Right-click on the Runtime Environment created above in the 'Runtime Explorer' view, and select *Edit*
2. Click the `Advanced Options...` link
3. Look for `{{ book.wlpcfgDir }}` in the list. If the directory is not listed, we need to add it:
    1. Click New
    2. Select the `{{ book.wlpcfgDir }}` project
    3. Select *Finish*, *OK*, *Finish*
4. Back in the Runtime Explorer view, expand the target Runtime Environment if not already, and *Right-click* 
on the `{{ book.wlpcfgDir }}` user directory and select *New Server*.
5. The resulting dialog should be pre-populated with the `{{ book.wlpServerName }}` Liberty server (you may have to look for it in
the drop-down of available/unbound servers). 
6. Click *Finish*

TIP: The name for the resulting server shown in the Servers view can vary, you might opt to rename it from 
the Right-click menu to make it easier to identify.


==== Running Liberty and the sample application from WDT

1.  Select the `{{ book.appDir }}` project
2.  Right-click -> *Run As... -> Run On Server*
3.  Select the appropriate server (as created above) and select *Finish*
4.  Confirm web browser opens on {{ book.appURL }}[{{ book.appURL }}]

NOTE: Some versions of WDT incorrectly map the cdi-1.2 dependency to the CDI 1.0 Facet, which prevents the 
*Run As ...* operation in step 2 from succeeding. If this happens, Right-click on the `{{ book.appDir }}` project, 
and select *Properties*, then select *Project Facets* in the left-hand pane. Change the the 
"Context and dependency injection (CDI)" facet to use version 1.2, at which point, step 2 (above) should work. 
