== Eclipse / WDT

The WebSphere Developer Tools (WDT) for Eclipse can be used to control the server (start/stop/dump/etc.), but more importantly, WDT also provides:

* *Automatic incremental publish of applications* so that you can write and test your changes without restarting the server.
* *Content-assist for server configuration*. Liberty's server configuration is minimal, but the tools can help you find what you need and identify finger-checks, etc.
* Integration with Eclipse Debugger to step through your application code.

When running with WDT, a "loose configuration" war file will be generated and placed in the apps
directory of the configured server. This will instruct the server to use the classes from your 
project to serve the application. You don't need to go through a build step to change your application
or tweak something in the server's configuration: everything is updated seamlessly in the running server as you work.

We highly recommend the WDT tools for incremental development of web applications. 
https://developer.ibm.com/wasdev/downloads/liberty-profile-using-eclipse[Download and install WDT on Eclipse from http://wasdev.net].
